import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark text-foreground bg-background">
        <Providers>
          <Sidebar />
          <div className="w-full ">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
