import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/navbar/Navbar";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        {/* Font API */}
        <link
          href="https://api.fontshare.com/v2/css?f[]=general-sans@701,200,500,301,201,300,601,600,401,501,400,700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className="dark text-foreground bg-background">
        <Providers>
          <div className="lg:flex lg:flex-row flex-col">
            <Navbar />
            <div className="w-full h-full p-5">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
